# setup github workflow to run jest tests on pull requests.
# https://docs.github.com/en/actions/guides/building-and-testing-nodejs
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      node-version: 18.x
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true